### ISSUE TITLE
Levering

### ISSUE THREAD

**Issue by patped** [patped/web-oblig1#9]
Oppgaven:
Levering gjøres ved å opprette en link på Fronter i mappen Innlevering. Husk å
angi ditt navn og studentnr., eller gruppenr., i navnet på linken. Du skal altså ikke
laste opp noen filer fra siten i fronter, kun en link.
Last opp rapporten i Fronter. Husk å krysse av for alle gruppemedlemmer dersom
dere leverer som en gruppe.

**Comment by KoichaDev** [comment]
Vår 5 år siden gammal prosjekt! 😂

**Comment by patped** [comment]
Bedre sent enn aldri 😆
